# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af52e923d3c5e76a90b6de4a4d8c92c943ce52ab79f1eb21a51d6117a9d11950b318f3bd548ae883c0ba4bb9966b77bea39136248a4079db82890dfecafe85a5

test:
  secret_key_base: 6403acfd83aeccaa405240833812bdf39515526ff4bc78e07cb43eba05489618dbae48ba8f8888ba07e3a1ad0674b7151e8a34014d4f7d37bb231e548391555b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
